<?php
	function find_leader($user_id){
		global $conn,$log;
		$sql = "SELECT CONCAT(a.user_id,'-', a.first_name) AS atasan1,CONCAT(b.user_id,'-', b.first_name) AS atasan2
				FROM dcoll_user a JOIN dcoll_user b ON(a.atasan = b.user_id)
				WHERE a.user_id = ?";
		//capture error and log to file
		try {
            $stmt_leader = $conn->prepare($sql);
            $stmt_leader->bind_param("s", $user_id);

            // Execute the statement
            $stmt_leader->execute();
            $stmt_leader->store_result();
            // Bind result variables
            $stmt_leader->bind_result($atasan1,$atasan2);
            $stmt_leader->fetch();
            $arr_atasan = array("atasan1"=>$atasan1,"atasan2"=>$atasan2);
            $stmt_leader->close();
            return $arr_atasan;
		}catch(Exception $e) {
			$log->LogError("Error: $e");
			$log->LogError("SQL: $sql");
			exit();
		}

	}
  function get_email_auth(){
        global $conn,$log;
        global $smtp_host;
		global $smtp_port;
        global $smtp_user;
        global $smtp_pass;

        $sql = "select id,value from dcoll_configuration where id like '%SMTP%'";
        try {
			$stmt = $conn->prepare($sql);
			$stmt->execute();
			$stmt->store_result();
			$stmt->bind_result($id,$value);
			//processing stored result
			while ($stmt->fetch()) {
				switch($id){
					case 'SMTP_SERVER':
						$smtp_host = $value;
					break;
					case 'SMTP_PORT':
						$smtp_port = $value;
					break;
					case 'SMTP_USER':
						$smtp_user = $value;
					break;
					case 'SMTP_PASS':
						$smtp_pass = $value;
					break;
				}
			}
            $stmt->free_result();
            $stmt->close();
		} catch (Exception $e) {
			$log->LogError("Error: %s\n", $e);
		}

    }
    function send_email_PL($status,$keterangan,$back_date = null){
        global $log;
		$date_now = date('d-M-Y H:i:s');
		//$mail_recipient = "aicms@cimbniaga.co.id";
		global $smtp_host;
		global $smtp_port;
		$mail_recipient = "Sanjaya@mylab.local";

        $mail = new PHPMailer();
		 $body = "AICMS BOD PL Status &nbsp;: <strong>$status</strong> ($date_now)
<table><tr><td>
Description </td><td>: $keterangan
</td></tr><tr><td>
File Name PL</td><td>:: BOD_AICMS_PL_$back_date.txt 
</td></tr><tr><td>
File Name PL Prev </td><td>:: BOD_AICMS_PL_PREV_$back_date.txt
</td></tr><tr><td>
File Name SYARIAH</td><td>:: BOD_AICMS_SYA_$back_date.txt 
</td></tr><tr><td>
File Name SYARIAH Prev </td><td>:: BOD_AICMS_SYA_PREV_$back_date.txt
</td></tr><tr><td>
File Name OUT</td><td>:: BOD_AICMS_OUT_$back_date.txt 
</td></tr><tr><td>
File Name OUT Prev </td><td>:: BOD_AICMS_OUT_PREV_$back_date.txt

</td></tr>
</table>
<br><br><br>Generated By<br><br>AICMS";

//echo  $body."\n";
        $mail->IsSMTP(); // telling the class to use SMTP
        $mail->SMTPDebug  = 2;                     // enables SMTP debug information (for testing)
                                                   // 1 = errors and messages
                                                   // 2 = messages only

		$mail->Host       =  $smtp_host;//'newsmtp.cimbniaga.co.id'; // sets the SMTP server
        $mail->Port       = $smtp_port;                    // set the SMTP port for the GMAIL server

        $mail->SetFrom('noreply-aicms-sit@mylab.local');

        $mail->Subject    = "[AICMS] BOD PL Process Info";


        $mail->MsgHTML($body);

        $ar_address = explode(";",$mail_recipient);
        foreach($ar_address as $address){
                $mail->AddAddress($address, $address);
        }

        // $mail->AddAttachment($logfile);      // attachment

         if(!$mail->Send()) {
        //      logadd("  Mailer Error\n");
          $log->LogError( "Mailer Error: " . $mail->ErrorInfo);
        } else {
        //      logadd("  Email message sent!\n");
        $log->LogInfo( "Message sent!");
        } 
}	

    function send_email($status,$keterangan,$back_date = null){
        $date_now = date('d-M-Y H:i:s');
        global $smtp_host;
        global $smtp_port;
        global $log;
        $mail_recipient = "neofinnone@mylab.local";

        $mail = new PHPMailer();
        
        $body = "AICMS BOD CC Status &nbsp;: <strong>$status</strong> ($date_now)
<br><br>
Description &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: $keterangan
<br><br>
File Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: BOD_AICMS_CC_$back_date.txt 
<br><br>
File Name Prev &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: BOD_AICMS_CC_PREV_$back_date.txt
<br><br><br>Generated By<br><br>AICMS";
    /*  $body = 'Berikut status dari hasil BOD AICMS hari ini :<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : '.$status.'<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Keterangan &nbsp;&nbsp; : '.$keterangan.'.<br><br><br>Generated By<br><br>AICMS'; */
        $mail->IsSMTP(); // telling the class to use SMTP
        $mail->SMTPDebug  = 1;                     // enables SMTP debug information (for testing)
                                                // 1 = errors and messages
                                                // 2 = messages only
        //$mail->SMTPAuth   = true;                  // enable SMTP authentication

        $mail->Host       =  $smtp_host;//'newsmtp.cimbniaga.co.id'; // sets the SMTP server
        $mail->Port       = $smtp_port;                    // set the SMTP port for the GMAIL server
        // $mail->Username   = $mail_user; // SMTP account username
        // $mail->Password   = $mail_pass;        // SMTP account password

        $mail->SetFrom('neofinnone@mylab.local');

        $mail->Subject    = "[AICMS] BOD CC Process Info";
		$log->LogInfo("Mail Body :$body");

        $mail->MsgHTML($body);

        $ar_address = explode(";",$mail_recipient);
        foreach($ar_address as $address){
                $mail->AddAddress($address, $address);
        }
        // $mail->AddAttachment($logfile);      // attachment

        if(!$mail->Send()) {
            $log->LogError("  Mailer Error\n". $mail->ErrorInfo);
        
        } else {
            $log->LogInfo("  Email message sent!\n");
        
        }
}
    function send_email_general($subject,$body){
        global $log;
		$date_now = date('d-M-Y H:i:s');
		 $mail_recipient = "neofinnone@mylab.local";
		global $smtp_host;
		global $smtp_port;

        $mail = new PHPMailer();
        $mail->IsSMTP(); // telling the class to use SMTP
        $mail->SMTPDebug  = 1;                     // enables SMTP debug information (for testing)
                                                   // 1 = errors and messages
                                                   // 2 = messages only
		$mail->Host       =  $smtp_host;//'newsmtp.cimbniaga.co.id'; // sets the SMTP server
        $mail->Port       = $smtp_port;                    // set the SMTP port for the GMAIL server
		
		echo "smtp sett $smtp_host : $smtp_port ======\n";
        // $mail->Username   = $mail_user; // SMTP account username
        // $mail->Password   = $mail_pass;        // SMTP account password

        $mail->SetFrom('neofinnone@mylab.local');
        $mail->Subject    = $subject;


        $mail->MsgHTML($body);

        $ar_address = explode(";",$mail_recipient);
        foreach($ar_address as $address){
                $mail->AddAddress($address, $address);
        }

        // $mail->AddAttachment($logfile);      // attachment

        if(!$mail->Send()) {
            $log->LogInfo("  Mailer Error\n". $mail->ErrorInfo);
        } else {
            $log->LogInfo("  Email message sent!\n");
        }
}	

function get_ftp_server_data($ftp_id){

    global $conn,$log;
     $sql = "SELECT ftp_server,user as ftp_user_name,password as ftp_user_pass,server_path  FROM dcoll_ftp_parameter WHERE id = ?";
     $stmt_ftp = $conn->prepare($sql);
     $stmt_ftp->bind_param("s", $ftp_id);
     $stmt_ftp->execute();
     $stmt_ftp->bind_result($server_path,$ftp_user_name,$ftp_user_pass,$ftp_server);
     $stmt_ftp->fetch();
     $stmt_ftp->close();
     $ftp_user_pass = encrypt_decrypt('decrypt',$ftp_user_pass);
     $ftp_data = array("server_path"=>$server_path,"ftp_user_name"=>$ftp_user_name,"ftp_user_pass"=>$ftp_user_pass,"ftp_server"=>$ftp_server);
   //  var_dump($ftp_data);
     return $ftp_data;
}

function put_files_by_curl($file_name,$ftp_id){
    global  $conn,$log;	
    global $ftp_server;
    global $ftp_user_name;
    global $ftp_user_pass;	
    global $server_path;

    $sql = "SELECT ftp_server,user as ftp_user_name,password as ftp_user_pass,server_path FROM dcoll_ftp_parameter WHERE id =?";
    $stmt_ftp = $conn->prepare($sql);
    $stmt_ftp->bind_param("s", $ftp_id);
    $stmt_ftp->execute();
    $stmt_ftp->bind_result($server_path,$ftp_user_name,$ftp_user_pass,$ftp_server);
    $stmt_ftp->fetch();
    $stmt_ftp->close();
    $ftp_user_pass = encrypt_decrypt('decrypt',$ftp_user_pass);

//echo 'ftps://'.$ftp_server.$server_path.basename($file_name)."\n";
//echo $ftp_user_name.':'.$ftp_user_pass."\n";
    
    $ftp_certificate = '/var/www/html/aicms/bod/certificate.pem';
    $ret = 0;
    $destinantion_url = 'ftps://'.$ftp_server.$server_path.basename($file_name);
    $log->LogDebug(">>> Uploading file $file_name to $destinantion_url");
    while(!$ret){
        // set up basic connection
    
        $file = fopen($file_name,'r');
        $ch = curl_init();

    //	curl_setopt($ch,CURLOPT_VERBOSE, TRUE);
        
        curl_setopt($ch,CURLOPT_URL,$destinantion_url);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch,CURLOPT_USERPWD,$ftp_user_name.':'.$ftp_user_pass);
        curl_setopt($ch,CURLOPT_TIMEOUT, 0);
        curl_setopt($ch,CURLOPT_CONNECTTIMEOUT, 0);
        
        curl_setopt($ch,CURLOPT_UPLOAD, 1);
        curl_setopt($ch,CURLOPT_INFILE, $file);
        curl_setopt($ch,CURLOPT_INFILESIZE, filesize($file_name));
        
        curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch,CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($ch,CURLOPT_CAINFO, $ftp_certificate);

        $upload_result = curl_exec($ch);
        $upload_info = curl_getinfo($ch);
        $error_no = curl_errno($ch);
        $error_msg = curl_error($ch);
        curl_close($ch);
        if($error_no == 0){
            $log->LogDebug(">>> Successfully put $file_name to ".$ftp_server.$server_path."/".basename($file_name));
            $ret = 1;
        }
        else{
            $log->LogError(">>>Failed to put $file_name with error : $error_msg | $error_no ");
            sleep(30);
            continue;
        }
        
        fclose($file);
    }	

    
};


function sendFileOverFTPS($localFile,$ftp_id)
{
    // Establish an SSL-FTP connection
    global  $conn,$log;	

    $sql = "SELECT ftp_server,user as ftp_user_name,password as ftp_user_pass,server_path FROM dcoll_ftp_parameter WHERE id =?";
    $stmt_ftp = $conn->prepare($sql);
    $stmt_ftp->bind_param("s", $ftp_id);
    $stmt_ftp->execute();
    $stmt_ftp->bind_result($server_path,$ftp_user_name,$ftp_user_pass,$ftp_server);
    $stmt_ftp->fetch();
    $stmt_ftp->close();
    $ftp_user_pass = encrypt_decrypt('decrypt',$ftp_user_pass);
    //echo $ftp_user_pass."\n";
    $connection = ftp_ssl_connect($ftp_server);

    if (!$connection) {
        $log->LogError("Could not connect to the FTP server $ftp_server");
        return false;

    }

    // Login to the FTP server with given username and password
    $login = ftp_login($connection, $ftp_user_name, $ftp_user_pass);

    if (!$login) {
        ftp_close($connection);
        $log->LogError("Could not log in to the FTP server $ftp_user_name @ $ftp_server ");
        return false;
    }

    // Set passive mode
    ftp_pasv($connection, true);

    // Upload the file
    $destinantion_url = $server_path.basename($localFile);
    $upload = ftp_put($connection, $destinantion_url, $localFile, FTP_BINARY);

    if (!$upload) {
        ftp_close($connection);
        $log->LogError("Could not upload the file $localFile");
        return false;
    }

    // Close the connection
    ftp_close($connection);
    $log->LogDebug(">>> Successfully put $localFile to $ftp_server:/$destinantion_url");
    return true;
}

function FTPS_list($ftp_id)
{
    // Establish an SSL-FTP connection
    global  $conn,$log;	

    $sql = "SELECT ftp_server,user as ftp_user_name,password as ftp_user_pass,server_path FROM dcoll_ftp_parameter WHERE id =?";
    $stmt_ftp = $conn->prepare($sql);
    $stmt_ftp->bind_param("s", $ftp_id);
    $stmt_ftp->execute();
    $stmt_ftp->bind_result($server_path,$ftp_user_name,$ftp_user_pass,$ftp_server);
    $stmt_ftp->fetch();
    $stmt_ftp->close();
    $ftp_user_pass = encrypt_decrypt('decrypt',$ftp_user_pass);
    //echo $ftp_user_pass."\n";
    $connection = ftp_ssl_connect($ftp_server);

    if (!$connection) {
        $log->LogError("Could not connect to the FTP server $ftp_server");
        return false;

    }

    // Login to the FTP server with given username and password
    $login = ftp_login($connection, $ftp_user_name, $ftp_user_pass);

    if (!$login) {
        ftp_close($connection);
        $log->LogError("Could not log in to the FTP server $ftp_user_name @ $ftp_server ");
        return false;
    }

    // Set passive mode
    ftp_pasv($connection, true);

    // Upload the file
    $buff = ftp_rawlist($connection, $server_path);
    // output the buffer
    print_r($buff);

    // Close the connection
    ftp_close($connection);
    return true;
}
?>